import 'dotenv/config';
import mongoose from 'mongoose';
import { User } from './models/User.js';
import { Transaction } from './models/Transaction.js';
import { Budget } from './models/Budget.js';
import { Goal } from './models/Goal.js';
import { MonthlyWrapped } from './models/MonthlyWrapped.js';
import { computeWrappedStats, completedMonths } from './lib/computeWrapped.js';

const EMAIL = process.argv[2];
if (!EMAIL) {
  console.error('Usage: pnpm seed <email>');
  process.exit(1);
}

// Date helper: by default produces a date in the CURRENT month/year so the
// seeded data always looks recent (audit M3 — was hard-coded to May 2026).
// Pass month/year overrides for the historical demo months below.
const NOW = new Date();
function d(day: number, month: number = NOW.getMonth(), year: number = NOW.getFullYear()) {
  return new Date(year, month, day);
}

interface SeedTx {
  title: string;
  amount: number;
  type: 'income' | 'expense';
  category?: string;
  date: Date;
  note?: string;
  mood?: string;
  essential?: boolean;
  paymentMethod?: string;
}

const TRANSACTIONS: SeedTx[] = [
  // ── Income ──────────────────────────────────────────────────────────
  { title: 'Monthly salary', amount: 3200, type: 'income', date: d(1), note: '' },
  {
    title: 'Freelance income',
    amount: 450,
    type: 'income',
    date: d(6),
    note: 'Web design project',
  },

  // ── Food & Drink ─────────────────────────────────────────────────────
  {
    title: 'Weekly groceries',
    amount: 112.4,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: d(1),
  },
  {
    title: 'Grocery top-up',
    amount: 34.2,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: d(4),
  },
  {
    title: 'Coffee',
    amount: 6.5,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Debit',
    date: d(2),
  },
  {
    title: 'Brunch',
    amount: 18.0,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Debit',
    date: d(3),
  },
  {
    title: 'Takeaway delivery',
    amount: 32.5,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'meh',
    paymentMethod: 'Credit',
    date: d(5),
  },
  {
    title: 'Dinner out',
    amount: 58.0,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Credit',
    date: d(7),
  },
  {
    title: 'Lunch',
    amount: 13.9,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'okay',
    paymentMethod: 'Cash',
    date: d(8),
  },

  // ── Entertainment ────────────────────────────────────────────────────
  {
    title: 'Movie tickets',
    amount: 36.0,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Credit',
    date: d(3),
  },
  {
    title: 'Music streaming',
    amount: 11.99,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Credit',
    date: d(1),
  },
  {
    title: 'Video game',
    amount: 24.99,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'regret',
    paymentMethod: 'Debit',
    date: d(6),
  },
  {
    title: 'Drinks with friends',
    amount: 22.0,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Cash',
    date: d(9),
  },
  {
    title: 'Concert tickets',
    amount: 89.0,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Credit',
    date: d(10),
  },
  {
    title: 'Lunch',
    amount: 14.5,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'okay',
    paymentMethod: 'Cash',
    date: d(10),
  },
  {
    title: 'Coffee',
    amount: 6.5,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Debit',
    date: d(11),
  },
  {
    title: 'Grocery top-up',
    amount: 28.4,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: d(11),
  },
  {
    title: 'Rideshare',
    amount: 15.0,
    type: 'expense',
    category: 'transport',
    essential: false,
    mood: 'meh',
    paymentMethod: 'Credit',
    date: d(12),
  },
  {
    title: 'Lunch',
    amount: 13.0,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'okay',
    paymentMethod: 'Cash',
    date: d(12),
  },

  // ── Transport ────────────────────────────────────────────────────────
  {
    title: 'Public transport',
    amount: 40.0,
    type: 'expense',
    category: 'transport',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: d(1),
  },
  {
    title: 'Petrol',
    amount: 85.3,
    type: 'expense',
    category: 'transport',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Debit',
    date: d(5),
  },
  {
    title: 'Rideshare',
    amount: 18.5,
    type: 'expense',
    category: 'transport',
    essential: false,
    mood: 'meh',
    paymentMethod: 'Credit',
    date: d(8),
  },

  // ── Shopping ─────────────────────────────────────────────────────────
  {
    title: 'Clothing',
    amount: 49.99,
    type: 'expense',
    category: 'shopping',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Credit',
    date: d(2),
  },
  {
    title: 'Household items',
    amount: 37.8,
    type: 'expense',
    category: 'shopping',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: d(7),
  },
  {
    title: 'Book',
    amount: 19.99,
    type: 'expense',
    category: 'shopping',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Debit',
    date: d(4),
  },

  // ── Health ───────────────────────────────────────────────────────────
  {
    title: 'Gym membership',
    amount: 49.9,
    type: 'expense',
    category: 'health',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Bank Transfer',
    date: d(1),
  },
  {
    title: 'Pharmacy',
    amount: 23.4,
    type: 'expense',
    category: 'health',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Debit',
    date: d(6),
  },

  // ── Rent / Bills ─────────────────────────────────────────────────────
  {
    title: 'Rent',
    amount: 950,
    type: 'expense',
    category: 'rent',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Bank Transfer',
    date: d(1),
  },
  {
    title: 'Power bill',
    amount: 88.7,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Bank Transfer',
    date: d(3),
  },
  {
    title: 'Internet bill',
    amount: 74.99,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Bank Transfer',
    date: d(2),
  },

  // ── January 2026 ────────────────────────────────────────────────────
  { title: 'Monthly salary', amount: 3200, type: 'income', date: new Date(2026, 0, 1) },
  {
    title: 'Rent',
    amount: 950,
    type: 'expense',
    category: 'rent',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 0, 1),
  },
  {
    title: 'Power bill',
    amount: 110.2,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 0, 3),
  },
  {
    title: 'Internet bill',
    amount: 74.99,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 0, 6),
  },
  {
    title: 'Gym membership',
    amount: 49.9,
    type: 'expense',
    category: 'health',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 0, 9),
  },
  {
    title: 'Weekly groceries',
    amount: 108.5,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 0, 4),
  },
  {
    title: 'Weekly groceries',
    amount: 95.3,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 0, 11),
  },
  {
    title: 'Weekly groceries',
    amount: 102.8,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 0, 18),
  },
  {
    title: 'Weekly groceries',
    amount: 98.6,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 0, 25),
  },
  {
    title: 'Coffee',
    amount: 5.5,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Debit',
    date: new Date(2026, 0, 7),
  },
  {
    title: 'Dinner out',
    amount: 62.0,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Credit',
    date: new Date(2026, 0, 20),
  },
  {
    title: 'Movie tickets',
    amount: 34.0,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Credit',
    date: new Date(2026, 0, 12),
  },
  {
    title: 'Pub night',
    amount: 38.0,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Cash',
    date: new Date(2026, 0, 27),
  },
  {
    title: 'Music streaming',
    amount: 11.99,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'okay',
    paymentMethod: 'Credit',
    date: new Date(2026, 0, 28),
  },
  {
    title: 'Petrol',
    amount: 82.4,
    type: 'expense',
    category: 'transport',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Debit',
    date: new Date(2026, 0, 15),
  },
  {
    title: 'New Year clothes',
    amount: 89.0,
    type: 'expense',
    category: 'shopping',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Credit',
    date: new Date(2026, 0, 21),
  },
  {
    title: 'Pharmacy',
    amount: 18.5,
    type: 'expense',
    category: 'health',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Debit',
    date: new Date(2026, 0, 29),
  },

  // ── February 2026 ───────────────────────────────────────────────────
  { title: 'Monthly salary', amount: 3200, type: 'income', date: new Date(2026, 1, 1) },
  {
    title: 'Rent',
    amount: 950,
    type: 'expense',
    category: 'rent',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 1, 1),
  },
  {
    title: 'Power bill',
    amount: 95.4,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 1, 3),
  },
  {
    title: 'Internet bill',
    amount: 74.99,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 1, 7),
  },
  {
    title: 'Phone bill',
    amount: 49.0,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 1, 13),
  },
  {
    title: 'Gym membership',
    amount: 49.9,
    type: 'expense',
    category: 'health',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 1, 9),
  },
  {
    title: 'Weekly groceries',
    amount: 104.2,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 1, 5),
  },
  {
    title: 'Weekly groceries',
    amount: 91.8,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 1, 12),
  },
  {
    title: 'Weekly groceries',
    amount: 99.6,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 1, 19),
  },
  {
    title: 'Weekly groceries',
    amount: 88.4,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 1, 26),
  },
  {
    title: "Valentine's dinner",
    amount: 96.0,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Credit',
    date: new Date(2026, 1, 14),
  },
  {
    title: 'Coffee',
    amount: 5.5,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Debit',
    date: new Date(2026, 1, 6),
  },
  {
    title: 'Concert tickets',
    amount: 89.0,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Credit',
    date: new Date(2026, 1, 27),
  },
  {
    title: 'Music streaming',
    amount: 11.99,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'okay',
    paymentMethod: 'Credit',
    date: new Date(2026, 1, 28),
  },
  {
    title: 'Impulse clothing haul',
    amount: 134.0,
    type: 'expense',
    category: 'shopping',
    essential: false,
    mood: 'regret',
    paymentMethod: 'Credit',
    date: new Date(2026, 1, 21),
  },
  {
    title: 'Rideshare',
    amount: 22.5,
    type: 'expense',
    category: 'transport',
    essential: false,
    mood: 'okay',
    paymentMethod: 'Credit',
    date: new Date(2026, 1, 16),
  },

  // ── March 2026 ──────────────────────────────────────────────────────
  { title: 'Monthly salary', amount: 3200, type: 'income', date: new Date(2026, 2, 1) },
  {
    title: 'Freelance income',
    amount: 450,
    type: 'income',
    date: new Date(2026, 2, 12),
    note: 'Web design project',
  },
  {
    title: 'Rent',
    amount: 950,
    type: 'expense',
    category: 'rent',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 2, 1),
  },
  {
    title: 'Power bill',
    amount: 88.7,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 2, 4),
  },
  {
    title: 'Internet bill',
    amount: 74.99,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 2, 7),
  },
  {
    title: 'Phone bill',
    amount: 49.0,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 2, 10),
  },
  {
    title: 'Gym membership',
    amount: 49.9,
    type: 'expense',
    category: 'health',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 2, 5),
  },
  {
    title: 'Weekly groceries',
    amount: 115.3,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 2, 7),
  },
  {
    title: 'Weekly groceries',
    amount: 109.8,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 2, 14),
  },
  {
    title: 'Weekly groceries',
    amount: 97.2,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 2, 21),
  },
  {
    title: 'Weekly groceries',
    amount: 103.4,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 2, 28),
  },
  {
    title: 'Midnight snack delivery',
    amount: 38.9,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'regret',
    paymentMethod: 'Credit',
    date: new Date(2026, 2, 18),
  },
  {
    title: 'Coffee',
    amount: 5.5,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Debit',
    date: new Date(2026, 2, 9),
  },
  {
    title: 'Weekend trip accommodation',
    amount: 210.0,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Credit',
    date: new Date(2026, 2, 15),
  },
  {
    title: 'Drinks with friends',
    amount: 45.0,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Cash',
    date: new Date(2026, 2, 25),
  },
  {
    title: 'Music streaming',
    amount: 11.99,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'okay',
    paymentMethod: 'Credit',
    date: new Date(2026, 2, 30),
  },
  {
    title: 'Petrol',
    amount: 79.6,
    type: 'expense',
    category: 'transport',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Debit',
    date: new Date(2026, 2, 15),
  },
  {
    title: 'Pharmacy',
    amount: 24.8,
    type: 'expense',
    category: 'health',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Debit',
    date: new Date(2026, 2, 31),
  },

  // ── April 2026 ──────────────────────────────────────────────────────
  { title: 'Monthly salary', amount: 3200, type: 'income', date: new Date(2026, 3, 1) },
  { title: 'Freelance income', amount: 300, type: 'income', date: new Date(2026, 3, 30) },
  {
    title: 'Rent',
    amount: 950,
    type: 'expense',
    category: 'rent',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 3, 1),
  },
  {
    title: 'Power bill',
    amount: 88.7,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 3, 4),
  },
  {
    title: 'Internet bill',
    amount: 74.99,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 3, 7),
  },
  {
    title: 'Phone bill',
    amount: 49.0,
    type: 'expense',
    category: 'utilities',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 3, 9),
  },
  {
    title: 'Gym membership',
    amount: 49.9,
    type: 'expense',
    category: 'health',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Bank Transfer',
    date: new Date(2026, 3, 5),
  },
  {
    title: 'Weekly groceries',
    amount: 111.6,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 3, 5),
  },
  {
    title: 'Weekly groceries',
    amount: 94.3,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 3, 12),
  },
  {
    title: 'Weekly groceries',
    amount: 101.7,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 3, 19),
  },
  {
    title: 'Weekly groceries',
    amount: 96.8,
    type: 'expense',
    category: 'food',
    essential: true,
    mood: 'okay',
    paymentMethod: 'Debit',
    date: new Date(2026, 3, 26),
  },
  {
    title: 'Coffee',
    amount: 5.5,
    type: 'expense',
    category: 'food',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Debit',
    date: new Date(2026, 3, 8),
  },
  {
    title: 'Movie tickets',
    amount: 36.0,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Credit',
    date: new Date(2026, 3, 13),
  },
  {
    title: 'Drinks with friends',
    amount: 32.0,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'glad',
    paymentMethod: 'Cash',
    date: new Date(2026, 3, 28),
  },
  {
    title: 'Music streaming',
    amount: 11.99,
    type: 'expense',
    category: 'entertainment',
    essential: false,
    mood: 'okay',
    paymentMethod: 'Credit',
    date: new Date(2026, 3, 29),
  },
  {
    title: 'New headphones',
    amount: 279.0,
    type: 'expense',
    category: 'shopping',
    essential: false,
    mood: 'regret',
    paymentMethod: 'Credit',
    date: new Date(2026, 3, 17),
    note: 'impulse buy',
  },
  {
    title: 'Hiking gear',
    amount: 145.0,
    type: 'expense',
    category: 'shopping',
    essential: false,
    mood: 'worth-it',
    paymentMethod: 'Credit',
    date: new Date(2026, 3, 22),
  },
  {
    title: 'Petrol',
    amount: 85.3,
    type: 'expense',
    category: 'transport',
    essential: true,
    mood: 'meh',
    paymentMethod: 'Debit',
    date: new Date(2026, 3, 15),
  },
];

const BUDGETS = [
  { category: 'food', monthlyLimit: 400, isPublic: true },
  { category: 'entertainment', monthlyLimit: 200, isPublic: true },
  { category: 'transport', monthlyLimit: 160, isPublic: false },
  { category: 'shopping', monthlyLimit: 150, isPublic: false },
  { category: 'health', monthlyLimit: 100, isPublic: true },
];

const GOALS = [
  {
    name: 'Emergency fund',
    targetAmount: 5000,
    currentAmount: 1850,
    deadline: new Date(2026, 11, 31),
    isPublic: false,
  },
  {
    name: 'New laptop',
    targetAmount: 2200,
    currentAmount: 920,
    deadline: new Date(2026, 8, 1),
    isPublic: false,
  },
  {
    name: 'Japan holiday',
    targetAmount: 4500,
    currentAmount: 600,
    deadline: new Date(2027, 2, 1),
    isPublic: true,
  },
];

async function seed() {
  const uri = process.env.MONGO_URI ?? 'mongodb://localhost:27017/bscamdd';
  await mongoose.connect(uri);
  console.log('Connected to MongoDB');

  const user = await User.findOne({ email: { $regex: new RegExp(`^${EMAIL}$`, 'i') } });
  if (!user) {
    console.error(`No user found with email: ${EMAIL}`);
    console.error('Make sure you have signed up first, then re-run this script.');
    process.exit(1);
  }
  const userId = String(user._id);
  console.log(`Seeding for: ${user.email} (${userId})`);

  const [txDel, budgetDel, goalDel, wrappedDel] = await Promise.all([
    Transaction.deleteMany({ userId }),
    Budget.deleteMany({ userId }),
    Goal.deleteMany({ userId }),
    MonthlyWrapped.deleteMany({ userId }),
  ]);
  console.log(
    `Cleared ${txDel.deletedCount} transactions, ${budgetDel.deletedCount} budgets, ${goalDel.deletedCount} goals, ${wrappedDel.deletedCount} wrapped`,
  );

  const txDocs = TRANSACTIONS.map((t) => ({ ...t, userId, amount: Number(t.amount) }));
  const [txs, budgets, goals] = await Promise.all([
    Transaction.insertMany(txDocs),
    Budget.insertMany(BUDGETS.map((b) => ({ ...b, userId }))),
    Goal.insertMany(GOALS.map((g) => ({ ...g, userId }))),
  ]);

  // Generate wrapped for all completed months from seeded transactions
  const allTxns = await Transaction.find({ userId });
  const months = completedMonths(allTxns);
  const wrappedDocs = months.map(({ year, month }) => {
    const monthTxns = allTxns.filter((t) => {
      const d = new Date(t.date);
      return d.getFullYear() === year && d.getMonth() + 1 === month;
    });
    return { userId, year, month, stats: computeWrappedStats(monthTxns), generatedAt: new Date() };
  });
  const wrapped = await MonthlyWrapped.insertMany(wrappedDocs);

  console.log(`✓ Created ${txs.length} transactions`);
  console.log(`✓ Created ${budgets.length} budgets`);
  console.log(`✓ Created ${goals.length} goals`);
  console.log(`✓ Generated ${wrapped.length} wrapped months`);
  console.log('Done!');

  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
